### ISSUE TITLE
Getting errors while installing canvas-to-pixels

### ISSUE THREAD

**Issue by utkarsh447** [twolfson/canvas-to-pixels#3]
Installed these dependencies
`sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++`

Also, installed canvas@1.6.5
Still getting errors
Before this, a long list of errors, 
but last ones are these
```
make: Leaving directory `/home/utkarsh/nodecanvas/node_modules/canvas-to-pixels/node_modules/canvas/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/utkarsh/nodecanvas/node_modules/canvas-to-pixels/node_modules/canvas
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by twolfson** [comment]
Since both `1.1.6` and `1.6.5` fail on your machine, it's likely missing a dependency. Can you try cloning their repo, set it up, and see where the failures occur?

https://github.com/Automattic/node-canvas/tree/v1.x#testing
